source 'https://rubygems.org'

gem 'sinatra'
gem 'activerecord'
gem 'activerecord-import'
gem 'sqlite3'
gem 'active_model_serializers', path: '/home/arne/github/active_model_serializers' #github: 'rails-api/active_model_serializers'
